# Generated by Django 4.2.2 on 2023-07-12 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'plan',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.plan'),
                ),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='current_version',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='current_version',
                to='plan.planversion',
            ),
        ),
        migrations.AlterField(
            model_name='rule',
            name='plan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='rules',
                to='plan.planversion',
            ),
        ),
    ]
