# Generated by Django 4.2.2 on 2023-06-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
