# Generated by Django 4.2.2 on 2023-06-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('plan', '0002_rule_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='query_embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
