# Generated by Django 4.2.2 on 2023-07-14 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('plan', '0002_plan_archived_planversion_plan_current_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planversion',
            name='description',
        ),
    ]
