# Generated by Django 4.2.2 on 2023-07-14 18:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('plan', '0003_remove_planversion_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='description',
        ),
    ]
