# Generated by Django 4.2.2 on 2023-06-24 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('plan', '0003_alter_rule_query_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='plan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='rules',
                to='plan.plan',
            ),
        ),
    ]
