# Generated by Django 4.2.3 on 2023-07-26 14:44

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pineconeasset',
            name='api_key',
            field=fernet_fields.fields.EncryptedCharField(max_length=256),
        ),
    ]
