# Generated by Django 4.2.3 on 2023-08-21 13:22

import django.db.models.deletion
import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('asset', '0002_alter_pineconeasset_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpointAsset',
            fields=[
                (
                    'baseasset_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='asset.baseasset',
                    ),
                ),
                ('url', models.URLField(max_length=2048)),
                (
                    'authentication_method',
                    models.CharField(
                        choices=[('Basic', 'Basic'), ('Bearer', 'Bearer')],
                        default='Bearer',
                        max_length=10,
                    ),
                ),
                ('api_key', fernet_fields.fields.EncryptedCharField(max_length=256)),
                ('headers', models.JSONField(blank=True, null=True)),
                (
                    'body',
                    models.JSONField(blank=True, default={'data': '%query%'}, null=True),
                ),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('asset.baseasset',),
        ),
    ]
