# Generated by Django 4.2.3 on 2023-08-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('asset', '0003_apiendpointasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpointasset',
            name='description',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='apiendpointasset',
            name='timeout',
            field=models.IntegerField(default=30),
        ),
    ]
