# Generated by Django 4.2.3 on 2023-08-17 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('asset', '0003_apiendpointasset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiendpointasset',
            name='body',
        ),
    ]
