# Generated by Django 4.2.3 on 2023-08-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('asset', '0003_apiendpointasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiendpointasset',
            name='body',
            field=models.JSONField(blank=True, default='{"data": "%query%"}', null=True),
        ),
    ]
