# Generated by Django 4.2.3 on 2023-08-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Severity',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=64)),
                ('value', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=7)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
    ]
