# Generated by Django 4.2.3 on 2023-07-26 15:47

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='openai_key',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=100),
        ),
    ]
