# Generated by Django 4.2.3 on 2023-08-02 20:00

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0002_alter_profile_openai_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cohere_key',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=100),
        ),
    ]
