# Generated by Django 4.2.3 on 2023-08-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0003_profile_cohere_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='finding_preview_size',
            field=models.IntegerField(default=20, null=True),
        ),
    ]
