# Generated by Django 4.2.3 on 2023-09-13 12:53

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0004_profile_finding_preview_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='anthropic_api_key',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='openai_api_key',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=100),
        ),
    ]
