# Generated by Django 4.2.3 on 2023-08-17 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('severity', '0001_initial'),
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='severity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='severity.severity'),
        ),
    ]
