# Generated by Django 4.2.3 on 2023-08-16 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Severity',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=64)),
                ('value', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=7)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='rule',
            name='severity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.severity'),
        ),
    ]
