# Generated by Django 4.2.3 on 2023-08-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0002_severity_alter_rule_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='severity',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
