# Generated by Django 4.2.3 on 2023-08-21 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0002_alter_rule_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRule',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.RemoveField(
            model_name='rule',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='severity',
        ),
        migrations.CreateModel(
            name='RegexRule',
            fields=[
                (
                    'baserule_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='policy.baserule',
                    ),
                ),
                ('query_string', models.TextField()),
                ('query_embedding', models.TextField(blank=True, null=True)),
                ('regex_test', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('policy.baserule',),
        ),
    ]
