# Generated by Django 4.2.2 on 2023-07-14 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0002_policy_archived_policyversion_policy_current_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyversion',
            name='description',
        ),
    ]
