# Generated by Django 4.2.3 on 2023-08-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0004_delete_rule_baserule_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baserule',
            name='rule_type',
            field=models.CharField(default='regex', max_length=20),
            preserve_default=False,
        ),
    ]
