# Generated by Django 4.2.3 on 2023-08-25 16:24

import re

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0004_delete_rule_baserule_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiQueryRule',
            fields=[
                (
                    'baserule_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='policy.baserule',
                    ),
                ),
                ('task_description', models.TextField()),
                (
                    'acceptable_outcomes',
                    models.TextField(
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile('^\\d+(?:,\\d+)*\\Z'),
                                code='invalid',
                                message='Enter only digits separated by commas.',
                            )
                        ]
                    ),
                ),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('policy.baserule',),
        ),
    ]
