# Generated by Django 4.2.3 on 2023-08-28 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0005_multiqueryrule_outcome'),
        ('policy', '0005_regexresult_regexfinding'),
    ]

    operations = []
