# Generated by Django 4.2.3 on 2023-08-22 14:48

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0005_outcome_multiqueryrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiqueryrule',
            name='acceptable_outcomes',
        ),
        migrations.DeleteModel(
            name='Outcome',
        ),
        migrations.AddField(
            model_name='multiqueryrule',
            name='acceptable_outcomes',
            field=models.TextField(
                default=1,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^\\d+(?:,\\d+)*\\Z'),
                        code='invalid',
                        message='Enter only digits separated by commas.',
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
