# Generated by Django 4.2.3 on 2023-08-24 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0005_baserule_rule_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baserule',
            name='rule_type',
        ),
    ]
