# Generated by Django 4.2.3 on 2023-08-28 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0006_merge_20230828_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Outcome',
        ),
    ]
