# Generated by Django 4.2.3 on 2023-08-30 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0007_delete_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiqueryrule',
            name='attack_count',
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
