# Generated by Django 4.2.3 on 2023-09-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0009_multiqueryrule_attack_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiqueryrule',
            name='model_name',
            field=models.CharField(default='gpt-4-0613', max_length=256),
        ),
        migrations.AddField(
            model_name='multiqueryrule',
            name='model_service',
            field=models.CharField(default='OpenAI', max_length=256),
        ),
    ]
