# Generated by Django 4.2.2 on 2023-07-11 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=256)),
                (
                    'service',
                    models.CharField(
                        choices=[
                            ('OA', 'OpenAI'),
                            ('LH', 'Locally Hosted: NOT IMPLEMENTED'),
                        ],
                        max_length=2,
                    ),
                ),
                ('text', models.TextField()),
                ('vectors', models.JSONField()),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
