# Generated by Django 4.2.3 on 2023-07-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('embedding', '0002_alter_embedding_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedding',
            name='service',
            field=models.CharField(
                choices=[
                    ('OpenAI', 'OpenAI'),
                    ('Localhost', 'Locally Hosted: NOT IMPLEMENTED'),
                ],
                max_length=256,
            ),
        ),
    ]
