# Generated by Django 4.2.3 on 2023-08-30 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeryworker',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='celeryworker',
            name='celery_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celeryworker',
            name='last_ping',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
