# Generated by Django 4.2.3 on 2023-08-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('worker', '0002_celeryworker_available_celeryworker_celery_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celeryworker',
            old_name='last_ping',
            new_name='last_check',
        ),
        migrations.AddField(
            model_name='celeryworker',
            name='last_success',
            field=models.DateTimeField(null=True),
        ),
    ]
