# Generated by Django 4.2.3 on 2023-08-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('worker', '0003_rename_last_ping_celeryworker_last_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeryworker',
            name='active_jobs',
            field=models.IntegerField(default=0),
        ),
    ]
