# Generated by Django 4.2.2 on 2023-06-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
