# Generated by Django 4.2.3 on 2023-07-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policy", "0001_initial"),
        ("scan", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scan",
            name="policy",
        ),
        migrations.AddField(
            model_name="scan",
            name="policies",
            field=models.ManyToManyField(to="policy.policy"),
        ),
    ]
