# Generated by Django 4.2.2 on 2023-06-29 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("target", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plan", "0001_initial"),
        ("scan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="target.basetarget"
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="result",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="plan.rule"
            ),
        ),
    ]
