# Generated by Django 4.2.2 on 2023-07-07 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('target', '0001_initial'),
        ('policy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='target.basetarget'),
        ),
        migrations.AddField(
            model_name='scan',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='result',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.rule'),
        ),
        migrations.AddField(
            model_name='result',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan.scan'),
        ),
        migrations.AddField(
            model_name='finding',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan.result'),
        ),
    ]
