# Generated by Django 4.2.3 on 2023-07-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scan', '0002_scanassetfailure'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='source_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
