# Generated by Django 4.2.2 on 2023-06-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scan', '0002_alter_scan_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='celery_task_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
