# Generated by Django 4.2.2 on 2023-07-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scan', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
