# Generated by Django 4.2.2 on 2023-06-25 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('plan', '0004_alter_rule_plan'),
        ('scan', '0003_scan_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='plan',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='plan.plan'),
            preserve_default=False,
        ),
    ]
