# Generated by Django 4.2.3 on 2023-08-07 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('asset', '0002_alter_pineconeasset_api_key'),
        ('scan', '0003_finding_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanasset',
            name='asset',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='scan_assets',
                to='asset.baseasset',
            ),
        ),
    ]
