# Generated by Django 4.2.3 on 2023-07-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scan', '0003_scan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(
                choices=[
                    ('Queued', 'Queued'),
                    ('Running', 'Running'),
                    ('Complete', 'Complete'),
                    ('Failed', 'Failed'),
                ],
                default='Queued',
                max_length=32,
            ),
        ),
    ]
