# Generated by Django 4.2.3 on 2023-08-16 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0001_initial'),
        ('asset', '0002_alter_pineconeasset_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scan', '0004_alter_scanasset_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTemplate',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='scanasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.baseasset'),
        ),
        migrations.CreateModel(
            name='ScanVersion',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('number', models.IntegerField(default=1)),
                (
                    'assets',
                    models.ManyToManyField(related_name='scan_assets', to='asset.baseasset'),
                ),
                ('policies', models.ManyToManyField(to='policy.policy')),
                (
                    'scan',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='versions',
                        to='scan.scantemplate',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='scantemplate',
            name='current_version',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='current_version',
                to='scan.scanversion',
            ),
        ),
        migrations.AddField(
            model_name='scantemplate',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('Queued', 'Queued'),
                            ('Running', 'Running'),
                            ('Complete', 'Complete'),
                            ('Failed', 'Failed'),
                        ],
                        default='Queued',
                        max_length=32,
                    ),
                ),
                (
                    'scan_version',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='scan_runs',
                        to='scan.scanversion',
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='scanasset',
            name='scan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='scan_assets',
                to='scan.scanrun',
            ),
        ),
        migrations.DeleteModel(
            name='Scan',
        ),
    ]
