# Generated by Django 4.2.3 on 2023-07-21 19:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scan', '0004_alter_scan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='progress',
        ),
    ]
