# Generated by Django 4.2.3 on 2023-08-16 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('asset', '0002_alter_pineconeasset_api_key'),
        ('scan', '0005_scantemplate_alter_scanasset_asset_scanversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanasset',
            name='asset',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='scan_run_assets',
                to='asset.baseasset',
            ),
        ),
        migrations.AlterField(
            model_name='scanasset',
            name='scan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='run_assets',
                to='scan.scanrun',
            ),
        ),
    ]
