# Generated by Django 4.2.3 on 2023-08-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scan', '0006_alter_scanasset_asset_alter_scanasset_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanrun',
            name='status',
            field=models.CharField(
                choices=[
                    ('Queued', 'Queued'),
                    ('Running', 'Running'),
                    ('Complete', 'Complete'),
                    ('Failed', 'Failed'),
                    ('Canceled', 'Canceled'),
                ],
                default='Queued',
                max_length=32,
            ),
        ),
    ]
