# Generated by Django 4.2.3 on 2023-08-22 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0004_delete_rule_baserule_policy_and_more'),
        ('scan', '0007_alter_result_rule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Finding',
            new_name='RegexFinding',
        ),
        migrations.RenameModel(
            old_name='Result',
            new_name='RegexResult',
        ),
    ]
