# Generated by Django 4.2.3 on 2023-08-23 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scan', '0007_alter_result_rule'),
        ('scan', '0007_alter_scanrun_status'),
    ]

    operations = []
