# Generated by Django 4.2.3 on 2023-08-25 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scan', '0008_merge_20230823_1503'),
        ('scan', '0008_rename_finding_regexfinding_and_more'),
    ]

    operations = []
