# Generated by Django 4.2.3 on 2023-08-28 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scan', '0009_merge_20230825_1546'),
        ('scan', '0010_remove_regexresult_rule_and_more'),
    ]

    operations = []
