# Generated by Django 4.2.3 on 2023-09-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scan', '0011_merge_20230828_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrun',
            name='one_shot_celery_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='scanrun',
            name='status',
            field=models.CharField(
                choices=[
                    ('Queued', 'Queued'),
                    ('Running', 'Running'),
                    ('Complete', 'Complete'),
                    ('Failed', 'Failed'),
                    ('Canceled', 'Canceled'),
                    ('Scheduled', 'Scheduled'),
                    ('Skipped', 'Skipped'),
                ],
                default='Queued',
                max_length=32,
            ),
        ),
    ]
