# Generated by Django 4.2.3 on 2023-09-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('policy', '0009_multiqueryrule_attack_count'),
        ('scan', '0011_merge_20230828_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanversion',
            name='policy_versions',
            field=models.ManyToManyField(to='policy.policyversion'),
        ),
    ]
