# Generated by Django 4.2.3 on 2023-09-05 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('scan', '0013_alter_scanrun_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrun',
            name='one_shot_celery_task',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='django_celery_beat.periodictask',
            ),
        ),
    ]
